Repository cloudfoundry/community, pull requests merged in 2023-09, with the labels that each got.

#679 Clarify how role promotion process works for WG Areas
  toc/ROLES.md
Labels: toc

#683 Update docs.md
  toc/working-groups/docs.md
Labels: wg

#687 Archive repository bosh-package-java-release
  org/cloudfoundry.yml
  toc/working-groups/foundational-infrastructure.md
Labels: toc

#686 2023 cff charter revisions
  governing-board/charter.md
Labels: toc

#676 RFC: TOC can stand in for WG leads
  toc/rfc/rfc-draft-toc-stand-in-for-wg-lead.md
Labels: toc, rfc

#691 [ARI] Add temp MultiApps team for managing GitHub secrets
  org/cloudfoundry.yml
Labels: toc, wg

#693 Update app-runtime-platform.md
  toc/working-groups/app-runtime-platform.md
Labels: wg
