Repository cloudfoundry/community, pull requests merged in 2023-11, with the labels that each got.

#711 Add otel-collector-release repo
  org/cloudfoundry.yml
  toc/working-groups/app-runtime-platform.md
Labels: toc

#670 Promote Andrew Wittrock and Dave Walter as new CF-on-K8s leads
  toc/working-groups/cf-on-k8s.md
Labels: toc, wg

#710 Add kathap as capi approver
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#698 Promote chombium to ARP WG Logging & Metrics approver
  toc/working-groups/app-runtime-platform.md
Labels: wg

#694 Rename repo as we no longer use gke for the concourse
  org/cloudfoundry.yml
  toc/working-groups/foundational-infrastructure.md
Labels: wg
