Repository cloudfoundry/community, pull requests merged in 2023-12, with the labels that each got.

#680 Promote Michael Oleske to CLI approver
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#716 Add kevin-ortega to contributors.yml
  org/contributors.yml
Labels: toc

#720 Add Kevin Ortega as approver
  toc/working-groups/app-runtime-interfaces.md
Labels: toc

#717 Add bosh-ali-storage-cli project
  org/cloudfoundry.yml
  toc/working-groups/foundational-infrastructure.md
Labels: toc

#714 Update contributors.yml
  org/contributors.yml
Labels: toc

#723 Remove tarpinian from contributors
  org/contributors.yml
Labels: toc

#729 Add default branch for otel-collector-release
  org/cloudfoundry.yml
Labels: toc

#730 add bosh-apt-resources repo
  org/cloudfoundry.yml
  toc/working-groups/foundational-infrastructure.md
Labels: toc, wg

#715 Update audit event names in readiness healthcheck RFC
  toc/rfc/rfc-0020-readiness-healthchecks.md
Labels: toc

#722 Added Cryogenics-CI to the bot group
  toc/working-groups/app-runtime-platform.md
Labels: wg

#731 Promote Eric to execution lead for ARP
  toc/working-groups/app-runtime-platform.md
Labels: toc
