Repository cloudfoundry/community, pull requests merged in 2023-08, with the labels that each got.

#656 Update branch protection for the CF-on-K8s repositories
  org/branchprotection.yml
Labels: toc

#667 Update CAPI reviewers in app-runtime-interfaces.md
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#668 Request reviewer permissions for cf-java-client - Radoslav Tomov
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#630 [RFC 630] add readiness healthchecks for apps
  toc/rfc/rfc-draft-readiness-healthchecks.md
Labels: toc, rfc

#674 Disable enforcing branch-protection for admins
  org/branchprotection.yml
Labels: wg

#677 New docs wg
  toc/working-groups/WORKING-GROUPS.md
  toc/working-groups/app-runtime-interfaces.md
  toc/working-groups/app-runtime-platform.md
  toc/working-groups/docs.md
  toc/working-groups/foundational-infrastructure.md
Labels: toc
