Repository cloudfoundry/community, pull requests merged in 2024-01, with the labels that each got.

#733 Removes Anubhav and add Sumit;
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#741 New repo for performance tests BOSH errand
  org/cloudfoundry.yml
Labels: toc

#719 Update app-runtime-interfaces buildpacks approvers
  org/contributors.yml
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#734 Request for Diego Approver status
  toc/working-groups/app-runtime-platform.md
Labels: wg

#713 Implement inactive user management
  .github/workflows/org-inactive-user-management.yml
  org/org_management.py
  org/org_user_management.py
  org/readme.md
  org/requirements.txt
Labels: toc

#753 Add Vulnerability Management WG contributors
  org/contributors.yml
Labels: toc

#745 Add new Metric Store members
  org/contributors.yml
  toc/working-groups/app-runtime-platform.md
Labels: wg

#750 Archive garden-windows-ci repo
  org/cloudfoundry.yml
  toc/working-groups/app-runtime-platform.md
Labels: toc

#744 [ARI] Add geigerj0 as Autoscaler reviewer
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#718 Promote klaus-sap to UAA approver
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#757 [ARI] Update ARI artifacts in WORKING-GROUPS.md
  toc/working-groups/WORKING-GROUPS.md
Labels: toc

#755 [ARI] Add Stephan as ARI Execution Lead
  toc/working-groups/WORKING-GROUPS.md
  toc/working-groups/app-runtime-interfaces.md
Labels: toc

#759 Add "ARI WG Git Bot" to bots list
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#726 service-manangement-wg: Add temporary group for area bot with admin permissions
  org/cloudfoundry.yml
  org/contributors.yml
Labels: toc, wg

#764 Bump version of github actions
  .github/workflows/org-inactive-user-management.yml
  .github/workflows/org-management-check-prs.yml
  .github/workflows/org-management-peribolos-dump.yml
  .github/workflows/org-management.yml
  .github/workflows/project-sync.yml
  .github/workflows/remove-individual-access.yml
Labels: toc

#763 Archive the vanta-blackbox-release
  org/cloudfoundry.yml
  toc/working-groups/app-runtime-platform.md
Labels: toc

#761 Remove garden-dockerfiles from Runtime
  toc/working-groups/app-runtime-platform.md
Labels: toc

#756 Remove individual repo access via github action
  .github/workflows/remove-individual-access.yml
Labels: toc

#721 Add blgm as approver to app-runtime-interfaces
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#765 Allow org automation to delete up to 80% of users
  .github/workflows/org-management.yml
Labels: toc

#766 Revert allow deletion of more users
  .github/workflows/org-management.yml
Labels: toc
