Repository cloudfoundry/community, pull requests merged in 2024-06, with the labels that each got.

#875 add nitin as reviewer for bosh
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#861 Remove old + unused repos from app-platform-runtime WG
  org/branchprotection.yml
  org/cloudfoundry.yml
  toc/working-groups/app-runtime-platform.md
Labels: toc

#873 A temporaray team for uaa pipeline access at https://bosh.ci.cloudfou…
  org/cloudfoundry.yml
Labels: wg

#883 Move Duane May to UAA approver
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#896 Fix remove not existing uaa-ci repo listin
  org/cloudfoundry.yml
Labels: toc

#885 Adding MultiApps bot
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#898 Add myself, mingxiao, as a contributor and reviewer for Bosh
  org/contributors.yml
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#893 Add Jamie van Dyke as a reviewer
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#878 sm-wg: remove inactive members
  toc/working-groups/service-management.md
Labels: wg

#899 Move Anthony Dahanne to Buildpacks and Java tools approver
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#889 Change execution to the first Monday of a month
  .github/workflows/org-inactive-user-management.yml
Labels: toc

#890 Use a virtual environment for pip in org automation readme
  org/readme.md
Labels: toc

#904 Assign Ansh the Approver Role
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#906 Add Tmp Team to configure Prometheus Exporter Secrets
  org/cloudfoundry.yml
Labels: toc

#830 RFC to introduce system Cloud Native Buildpacks
  toc/rfc/rfc-draft-system-cnb.md
Labels: toc, rfc

#910 Update zoom link for ARI WG meeting
  toc/working-groups/WORKING-GROUPS.md
Labels: wg

#908 Update FIWG Disaster Recovery (BBR) area with folks from the BOSH area
  toc/working-groups/foundational-infrastructure.md
Labels: wg
