Repository cloudfoundry/community, pull requests merged in 2024-05, with the labels that each got.

#835 Add David Alvarado as CLI approver
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#804 [RFC] Add Support for File based Service Binding Information
  toc/rfc/rfc-draft-add-support-for-file-based-service-binding.md
Labels: toc, rfc

#841 Add Glenn Oppegard as a Reviewer to System Logging and Metrics
  org/contributors.yml
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#852 add nader-ziada as contributor and reviewer for bosh
  org/contributors.yml
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#844 Add weresch to contributors
  org/contributors.yml
Labels: toc

#848 Add samze to contributors
  org/contributors.yml
Labels: toc

#849 Add Joao to the contributors list
  org/contributors.yml
Labels: toc

#853 Add Tim Downey as a CLI reviewer
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#854 Add samze to reviewer of CAPI
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#855 Adding Greg Meyer as reviewer for bosh
  org/contributors.yml
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#856 Add stacks repos (responsability of Buildpacks team) to the branch protection exclusions
  org/branchprotection.yml
Labels: wg

#851 Add Duane May to Identity and Creds reviewers
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#862 Add samze to reviews of cli
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#826 Add Paul Spinrad
  toc/working-groups/docs.md
Labels: toc, wg

#843 Add Andrew Costa to Logging and Metrics reviewers
  toc/working-groups/app-runtime-platform.md
Labels: wg

#842 Add "Ausaf Ahmed" to Logging and Metrics Reviewers
  toc/working-groups/app-runtime-platform.md
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#840 Add Glenn Oppegard to Logging and Metrics Reviewers
  toc/working-groups/app-runtime-platform.md
Labels: wg

#839 Change from loewenstein to loewenstein-sap
  org/contributors.yml
  toc/working-groups/app-runtime-platform.md
  toc/working-groups/paketo.md
Labels: wg

#836 Add approvers to cnbapplifecycle
  toc/working-groups/app-runtime-platform.md
Labels: wg

#864 Remove myself
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#863 Remove myself
  toc/working-groups/service-management.md
Labels: wg
