Repository cloudfoundry/community, pull requests merged in 2024-10, with the labels that each got.

#988 archive the cpu-entitlement plugins
  org/cloudfoundry.yml
  toc/working-groups/app-runtime-platform.md
Labels: toc

#991 Add new approver for Prometheus
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#989 Add strehle to credhub
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#996 Add Prometheus CI Bot
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#995 Promote Jochen Ehret to CAPI Approver
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#941 [RFC] CF API v2 End of Life
  toc/rfc/rfc-draft-cfapiv2-eol.md
Labels: rfc

#946 [RFC] User Creation by Org Managers
  toc/rfc/app-runtime-interfaces/rfc-draft-user-creation-by-org-managers.md
Labels: rfc

#1003 Fix RFC PR for rfc-0027
  toc/rfc/rfc-0027-generic-per-route-features.md
Labels: rfc

#1002 Update foundational-infrastructure.md
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#997 Add Sascha Stojanovic as Reviewer
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#1012 Add myself to approvers list
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#1011 Add "Acceptance Tests - MTA" to branch protection checks
  org/branchprotection.yml
Labels: wg

#1010 Make RFC merge commit SHA required parameter for assign-rfc-number
  toc/rfc/README.md
  toc/rfc/assign-rfc-number.sh
Labels: toc

#1005 Remove the subfolder app-runtime-interfaces
  toc/rfc/rfc-0011-move-buildpacks-dependencies-to-cff.md
  toc/rfc/rfc-0033-user-creation-by-org-managers.md
Labels: rfc

#1008 [RFC0030] Updates
  toc/rfc/rfc-0030-add-support-for-file-based-service-binding.md
Labels: rfc

#1009 Update foundational-infrastructure.md
  toc/working-groups/foundational-infrastructure.md
Labels: wg
