Repository cloudfoundry/community, pull requests merged in 2024-04, with the labels that each got.

#800 Move the ali repositories into a sub area
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#806 Fix default branch of bosh-ali-cloud-cpi repo
  org/cloudfoundry.yml
Labels: toc

#805 [ARI] Set up RFC 0015-compliant branch protections for autoscaler repos
  org/branchprotection.yml
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#808 Update FI WG details
  toc/working-groups/WORKING-GROUPS.md
Labels: wg

#803 Add more details for refute options in inactive user pr
  org/org_user_management.py
Labels: toc

#810 split go-uaa
  toc/working-groups/foundational-infrastructure.md
Labels: toc

#743 rfc: generic per-route features
  toc/rfc/rfc-draft-generic-per-route-features.md
Labels: toc, rfc

#811 add xtreme-nitin-ravindran to contributors
  org/contributors.yml
Labels: toc

#809 wg-service-management: Update CSB members
  toc/working-groups/service-management.md
Labels: wg

#813 fix(app-autoscaler-release): allow admins to bypass required status checks
  org/branchprotection.yml
Labels: wg

#812 Add additional cli repos to temp-ari-cli-admins
  org/cloudfoundry.yml
Labels: wg

#819 Exclude CAPI CI related repos from branch protection
  org/branchprotection.yml
Labels: wg

#814 Update TOC meeting notes link
  toc/TOC.md
Labels: toc

#799 Enable branch protection automation for ARI WG
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#822 Adds bonzofenix as approver for autoscaler team
  org/cloudfoundry.yml
  org/contributors.yml
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#825 Add Monika Noeva as reviewer
  org/contributors.yml
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#829 Add Stefan Yonkov as reviewer
  org/contributors.yml
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#820 Add Duane May as a contributor
  org/contributors.yml
Labels: toc

#796 RFC to introduce Cloud Native Buildpacks lifecycle
  toc/rfc/rfc-draft-cnb-lifecycle.md
Labels: toc, rfc

#831 Remove emalm as an ARP WG execution lead
  toc/working-groups/app-runtime-platform.md
Labels: toc

#807 [RFC] Option to tunnel CF SSH through WebSockets
  toc/rfc/rfc-draft-ssh-over-ws.md
  toc/rfc/rfc-draft-ssh-over-ws/cf-ssh-over-websocket.drawio.png
Labels: toc, rfc
