Repository cloudfoundry/community, pull requests merged in 2024-11, with the labels that each got.

#1013 add back cf-bosh-ci-bot that was removed in #992
  org/contributors.yml
  toc/working-groups/foundational-infrastructure.md
Labels: toc

#1015 Update RFC rules to have a flat list of RFCs in the community repository
  toc/rfc/README.md
Labels: toc

#1016 [ARI] Modify autoscaler branch protection checks
  org/branchprotection.yml
Labels: wg-ari

#998 Inactive users to be removed from ARI WG
  toc/working-groups/app-runtime-interfaces.md
Labels: wg, wg-ari

#1021 Remove inactive user "jimconner"
  toc/working-groups/app-runtime-deployments.md
Labels: wg-ard

#1022 Remove inactive user "kmarkwardt-vmware"
  org/contributors.yml
  toc/working-groups/foundational-infrastructure.md
Labels: wg-fi

#1018 Add Sriram to CAPI reviewers
  org/contributors.yml
  toc/working-groups/app-runtime-interfaces.md
Labels: wg-ari

#1024 Create new repo `credhub-oss-ci`
  org/cloudfoundry.yml
  toc/working-groups/foundational-infrastructure.md
Labels: toc

#1026 [ARI] Add Lokowandtg as reviewer for Java Tools
  toc/working-groups/app-runtime-interfaces.md
Labels: wg-ari
