Repository cloudfoundry/community, pull requests merged in 2024-12, with the labels that each got.

#1017 Inactive users to be removed from ARI WG
  toc/working-groups/app-runtime-interfaces.md
Labels: wg, wg-ari

#1025 add "Ivan Protsiuk" to Logging and Metrics Reviewers
  toc/working-groups/app-runtime-platform.md
  toc/working-groups/foundational-infrastructure.md
Labels: wg-arp, wg-fi

#990 Correct approvers and reviewers lists
  toc/working-groups/paketo.md
Labels: wg, wg-paketo

#1032 Add Daniel Garnier-Moiroux as UAA contributor
  org/contributors.yml
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#1033 The BOSH workstation setup repository is not used any more
  org/cloudfoundry.yml
  toc/working-groups/foundational-infrastructure.md
Labels: toc
