Repository cloudfoundry/community, pull requests merged in 2024-02, with the labels that each got.

#768 Adds CI bot to working group
  toc/working-groups/foundational-infrastructure.md
Labels: wg

#769 [ARI] Add temp autoscaler team for managing GitHub secrets
  org/cloudfoundry.yml
Labels: toc, wg

#773 Add `salzmannsusan` to approvers of `Autoscaler`
  org/cloudfoundry.yml
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#747 Remove metric store team members who've left VMware
  org/contributors.yml
  toc/working-groups/app-runtime-platform.md
Labels: wg

#772 Add `geigerj0` to approvers of `Autoscaler`
  org/cloudfoundry.yml
  toc/working-groups/app-runtime-interfaces.md
Labels: wg

#771 Fix path to `contributions-for-user.sh` in example
  toc/ROLES.md
Labels: toc

#780 Remove @gcapizzi and @kieron-dev from their WGs
  org/contributors.yml
  toc/working-groups/WORKING-GROUPS.md
  toc/working-groups/app-runtime-platform.md
  toc/working-groups/cf-on-k8s.md
Labels: toc

#777 Add cf-cli-eng bot to App Runtime Interfaces
  toc/working-groups/app-runtime-interfaces.md
Labels: toc

#781 Move capi-bot to the CAPI working group
  toc/working-groups/app-runtime-interfaces.md
Labels: wg
