Repository cloudfoundry/community, pull requests merged in 2025-04, with the labels that each got.

#1111 Add Hamideh Amini Khezrabad to the contributors list
  orgs/contributors.yml
Labels: toc

#1110 Add julian-hj as a reviewer for BOSH
  toc/working-groups/foundational-infrastructure.md
Labels: wg-fi

#1119 Move Daniel Garnier-Moiroux to Java Tools approver
  toc/working-groups/app-runtime-interfaces.md
Labels: wg-ari

#1114 Archive bosh-io-stemcells-softlayer-index
  orgs/orgs.yml
  toc/working-groups/foundational-infrastructure.md
Labels: toc

#1116 Add Milena-Encheva to contributors.yaml
  orgs/contributors.yml
Labels: toc

#1118 Add Alexander Nicke (@a18e) as ARP Networking approver
  toc/working-groups/app-runtime-platform.md
Labels: wg-arp

#1128 Archive inactive FIWG repos
  orgs/orgs.yml
  toc/working-groups/foundational-infrastructure.md
Labels: toc

#1127 Add @peanball (Alexander Lais) as reviewer to Foundational Infrastructure
  toc/working-groups/foundational-infrastructure.md
Labels: wg-fi

#1130 Add nishad to bosh reviewers
  toc/working-groups/foundational-infrastructure.md
Labels: wg-fi

#1117 Add Deniz Tas to the contributors list
  orgs/contributors.yml
Labels: toc

#1131 fix: link to lead promotion
  toc/ROLES.md
Labels: toc
