Repository cloudfoundry/community, pull requests merged in 2025-03, with the labels that each got.

#1089 remove inactive ARP users
  toc/working-groups/app-runtime-platform.md
Labels: wg-arp

#1078 Move OSBAPI to ARI WG - Proposal
  toc/working-groups/app-runtime-interfaces.md
  toc/working-groups/service-management.md
Labels: toc, wg-ari

#1094 archive inlined routing-release submodules
  org/cloudfoundry.yml
  toc/working-groups/app-runtime-platform.md
Labels: toc, wg-arp

#1085 RFC: Password Deprecate Request
  toc/rfc/rfc-draft-deprecate-passwords.md
Labels: toc, rfc

#1097 Update iprotsiuk role to approver
  toc/working-groups/foundational-infrastructure.md
Labels: wg-fi

#1099 Update Duane May to go-uaa approver.
  toc/working-groups/foundational-infrastructure.md
Labels: wg-fi

#1103 fix: remove duplicate user
  toc/working-groups/app-runtime-platform.md
Labels: wg-arp

#1101 Use markdown checklists instead of tasklists for the RFC tracking template
  .github/ISSUE_TEMPLATE/rfc-issue-template.md
Labels: toc

#1102 Log the inactive users' Working Group information
  org/org_user_management.py
Labels: toc

#1077 rfc: IPv6 Dual Stack Support for Cloud Foundry
  toc/rfc/rfc-draft-ipv6-dual-stack-for-cf.md
Labels: toc, rfc

#1108 Revert "Unarchive docs-deploying-cf"
  org/cloudfoundry.yml
Labels: toc

#1098 remove approver
  toc/working-groups/foundational-infrastructure.md
Labels: wg-fi

#1105 Fix invalid yaml in template and improve
  .github/ISSUE_TEMPLATE/rfc-issue-template.md
Labels: toc

#1106 Adapt org management to rfc-0036
  .github/workflows/org-inactive-user-management.yml
  .github/workflows/org-management-check-prs.yml
  .github/workflows/org-management-ci.yml
  .github/workflows/org-management-peribolos-dump.yml
  .github/workflows/org-management.yml
  .github/workflows/project-sync.yml
  org/contributors.yml
  orgs/.flake8
  orgs/branchprotection.yml
  orgs/contributors.yml
  orgs/generate_working_group_projects_sync_config.sh
  orgs/org_management.py
  orgs/org_user_management.py
  orgs/orgs.yml
  orgs/orphaned_repos.sh
  orgs/pyproject.toml
  orgs/readme.md
  orgs/requirements-dev.txt
  orgs/requirements.txt
  orgs/test_org_management.py
  toc/ROLES.md
  toc/rfc/rfc-0007-repository-ownership.md
  toc/rfc/rfc-0008-role-change-process.md
  toc/rfc/rfc-0013-remove-nonstandard-github-teams.md
  toc/rfc/rfc-0025-define-criteria-and-removal-process-for-inactive-members.md
  toc/rfc/rfc-0036-multiple-github-orgs.md
Labels: toc
