Repository cloudfoundry/community, pull requests merged in 2025-01, with the labels that each got.

#1041 Create new app-runtime-platform-envs repo
  org/cloudfoundry.yml
  toc/working-groups/app-runtime-platform.md
Labels: toc

#1036 Add Ajita Jain as CredHub contributor
  org/contributors.yml
  toc/working-groups/foundational-infrastructure.md
Labels: wg-fi

#1039 Update RFC 0027: Unify load balancing property name
  toc/rfc/rfc-0027-generic-per-route-features.md
Labels: toc, rfc

#1044 Add Benjamin Guttmann as approver
  toc/working-groups/foundational-infrastructure.md
Labels: wg-fi

#1040 Move Daniel Garnier-Moiroux to UAA approver
  toc/working-groups/foundational-infrastructure.md
Labels: wg-fi

#1037 Add Joe Eltgroth as contributor
  org/contributors.yml
  toc/working-groups/foundational-infrastructure.md
Labels: wg-fi

#1045 Add Yusmen Zabanov to the cf-on-k8s working group
  org/contributors.yml
  toc/working-groups/cf-on-k8s.md
Labels: wg-cf-on-k8s

#1038 A new team member of the team supporting credhub at Broadcom
  org/contributors.yml
  toc/working-groups/foundational-infrastructure.md
Labels: wg-fi

#1052 Add credehub reviwers
  toc/working-groups/foundational-infrastructure.md
Labels: wg-fi

#1056 [ARI] Add Daniel Garnier-Moiroux as Java Tools contributor
  toc/working-groups/app-runtime-interfaces.md
Labels: wg-ari

#1053 Fix PR link of RFC 0028
  toc/rfc/rfc-0028-cnb-lifecycle.md
Labels: toc, rfc

#1048 wg-sm: archive service fabrik project
  org/cloudfoundry.yml
  toc/working-groups/service-management.md
Labels: toc

#1057 Validate repository ownership
  org/org_management.py
  org/test_org_management.py
Labels: toc

#1059 Remove app-runtime-interfaces-infrastructure from Docs WG
  toc/working-groups/docs.md
Labels: wg-doc

#1067 Add Oliver as reviewer for Cloud Foundry ARD working group
  toc/working-groups/app-runtime-deployments.md
Labels: wg-ard
