Repository cloudfoundry/community, pull requests merged in 2025-09, with the labels that each got.

#1256 [RFC] Document CF API V3 with OpenAPI
  toc/rfc/rfc-draft-document-cf-api-with-openapi.md
Labels: toc, rfc

#1298 Add Bhuvisha03 as a reviewer to Terraform provider cloudfoundry
  toc/working-groups/app-runtime-interfaces.md
Labels: wg-ari

#1305 Add Nishad as a approver to bosh and bosh adjacent projects
  toc/working-groups/foundational-infrastructure.md
Labels: wg-fi

#1295 Add Wei as Reviewer for Logging/Metrics
  toc/working-groups/app-runtime-platform.md
  toc/working-groups/foundational-infrastructure.md
Labels: wg-arp, wg-fi

#1316 Add Milena-Encheva as approver
  toc/working-groups/app-runtime-deployments.md
Labels: wg-ard
