Repository cloudfoundry/community, pull requests merged in 2025-08, with the labels that each got.

#1269 Add branch protection rules for uaa and uaa-release
  orgs/branchprotection.yml
Labels: toc

#1268 Request repository to work on #1256
  orgs/orgs.yml
  toc/working-groups/app-runtime-interfaces.md
Labels: toc

#1239 Add Plamen Bardarov as reviewier in App Runtime Interfaces WG
  toc/working-groups/app-runtime-interfaces.md
Labels: wg-ari

#1272 Disable enforcing branch-protection for homebrew-tap
  orgs/branchprotection.yml
Labels: toc

#1273 Assigning number 0043 to RFC from PR #1253
  toc/rfc/rfc-0043-cc-blobstore-storage-cli.md
Labels: toc

#1277 CredHub repos: Disable enforcing branch-protection for admins
  orgs/branchprotection.yml
Labels: toc

#1283 CredHub repo: Disable enforcing branch-protection for admins
  orgs/branchprotection.yml
Labels: toc

#1284 Archive winc-release submodules
  orgs/orgs.yml
  toc/working-groups/app-runtime-platform.md
Labels: toc

#1287 Add Ned Petrov as a BOSH reviewer
  toc/working-groups/foundational-infrastructure.md
Labels: wg-fi

#1279 Add Ivaylo Ivanov as a reviewer for BOSH
  toc/working-groups/foundational-infrastructure.md
Labels: wg-fi
